### ISSUE TITLE
Auctioneer not seeing bids, vaults stuck liquidating loop looking for bids

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/agoric-sdk#10667]
## Describe the bug

There are 3 vaults currently stuck in a state of liquidating. I can see auctions are running but the auctions are ignoring my bids.

1. stTIA 1 https://vstorage.agoric.net/?path=published.vaultFactory.managers.manager3.vaults.vault197&endpoint=https%3A%2F%2Fmain-a.rpc.agoric.net%3A443&height=null 
2. stTIA 2 https://vstorage.agoric.net/?path=published.vaultFactory.managers.manager3.vaults.vault195&endpoint=https%3A%2F%2Fmain-a.rpc.agoric.net%3A443&height=null
3. ATOM https://vstorage.agoric.net/?path=published.vaultFactory.managers.manager0.vaults.vault128&endpoint=https%3A%2F%2Fmain-a.rpc.agoric.net%3A443&height=null

Examining Auctions:

ATOM
brendanotoole@brendans-MacBook-Pro agoric-sdk % inter auction status --book 0                                                                                                                    
{
  "schedule": {
    "activeStartTime": "2024-12-10T20:00:03.000Z",
    "nextStartTime": "2024-12-10T21:00:03.000Z",
    "nextDescendingStepTime": "2024-12-10T20:18:03.000Z"
  },
  "book0": {
    "startPrice": "7.6359 IST/ATOM",
    "currentPriceLevel": "6.1087 IST/ATOM",
    "startProceedsGoal": "5.00056 IST",
    "remainingProceedsGoal": "5.00056 IST",
    "startCollateral": "0.866627 ATOM",
    "collateralAvailable": "0.866627 ATOM"
  },
  "params": {
    "DiscountStep": "5.00%",
    "ClockStep": "00:03:00",
    "LowestRate": "65.00%"
  }
}
brendanotoole@brendans-MacBook-Pro agoric-sdk % 

stTIA

brendanotoole@brendans-MacBook-Pro agoric-sdk % inter auction status --book 3
{
  "schedule": {
    "activeStartTime": "2024-12-10T20:00:03.000Z",
    "nextStartTime": "2024-12-10T21:00:03.000Z",
    "nextDescendingStepTime": "2024-12-10T20:21:03.000Z"
  },
  "book3": {
    "startPrice": "7.0752 IST/stTIA",
    "currentPriceLevel": "5.3064 IST/stTIA",
    "startProceedsGoal": "200.022388 IST",
    "remainingProceedsGoal": "200.022388 IST",
    "startCollateral": "47.81992 stTIA",
    "collateralAvailable": "47.81992 stTIA"
  },
  "params": {
    "DiscountStep": "5.00%",
    "ClockStep": "00:03:00",
    "LowestRate": "65.00%"
  }
}
brendanotoole@brendans-MacBook-Pro agoric-sdk %

my bids:

<img width="1200" alt="image" src="https://github.com/user-attachments/assets/b726fb8a-79ad-4d0e-9e0d-09936b67b3ba">

<img width="436" alt="image" src="https://github.com/user-attachments/assets/1984499f-05c6-48ae-85b3-35d446c78dc6">

## To Reproduce
1. Observe auctions running for ATOM and stTIA (via CLI)
2. Place bid via CLI a la 
```
brendanotoole@brendans-MacBook-Pro agoric-sdk % inter bid by-discount --discount 34 --give 10IST --maxBuy 30000ATOM --generate-only --from test-acct-14 --keyring-backend=test >spend-action.json
Now use `agoric wallet send ...` to sign and broadcast the offer.
brendanotoole@brendans-MacBook-Pro agoric-sdk % agd --node=https://main.rpc.agoric.net:443 tx swingset wallet-action --allow-spend "$(cat spend-action.json)" --chain-id=agoric-3 --fees=6000ubld --gas=auto --gas-adjustment=1.3 --from test-acct-14 --keyring-backend=test -b block
gas estimate: 188996
auth_info:
  fee:
    amount:
    - amount: "6000"
      denom: ubld
    gas_limit: "188996"
    granter: ""
    payer: ""
  signer_infos: []
  tip: null
body:
  extension_options: []
  memo: ""
  messages:
  - '@type': /agoric.swingset.MsgWalletSpendAction
    owner: agoric1la4yek5053r58e8z0kx86lspkj9cfsaarg5twv
    spend_action: '{"body":"#{\"method\":\"executeOffer\",\"offer\":{\"id\":\"bid-1733861830235\",\"invitationSpec\":{\"callPipe\":[[\"makeBidInvitation\",[\"$0.Alleged:
      BoardRemoteATOM brand\"]]],\"instancePath\":[\"auctioneer\"],\"source\":\"agoricContract\"},\"offerArgs\":{\"maxBuy\":{\"brand\":\"$0\",\"value\":\"+30000000000\"},\"offerBidScaling\":{\"denominator\":{\"brand\":\"$1.Alleged:
      BoardRemoteIST brand\",\"value\":\"+100\"},\"numerator\":{\"brand\":\"$1\",\"value\":\"+66\"}}},\"proposal\":{\"give\":{\"Bid\":{\"brand\":\"$1\",\"value\":\"+10000000\"}}}}}","slots":["board05557","board0257"]}'
  non_critical_extension_options: []
  timeout_height: "0"
signatures: []
confirm transaction before signing and broadcasting [y/N]: y
```
3 - watch auction keep running and bid not getting picked up

## Expected behavior
Bids should be picked up when auction is looking for bids to selling collateral for IST
