### ISSUE TITLE
As a user, I can run an ag-solo / wallet to connect to testnet dapps using a docker container

### ISSUE THREAD

**Issue by rowgraus** [Agoric/agoric-sdk#2697]
_p.s. see https://github.com/Agoric/agoric-sdk/wiki/Setting-up-an-Agoric-Dapp-Client-with-docker-compose --Dan_

**Comment by dckc** [comment]
I broke ground but didn't get very far. I don't have a very clear mental model of what's going on. Starting this at the end of the day doesn't help; perhaps it'll be clearer tomorrow. Or maybe you can clue me in. But if it's faster, feel freeo to go ahead and I'll review @michaelfig .

```
connolly@jambox:~/projects/agoric/agoric-sdk/packages/cosmic-swingset/docker/client$ docker-compose up
/usr/lib/python2.7/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Starting client_ag-solo_1 ... 
Starting client_ag-solo_1 ... done
Attaching to client_ag-solo_1
ag-solo_1  | SwingSet: controller: SwingSet global metering is enabled
ag-solo_1  | SwingSet: kernel: kernel message bootstrap: rejected {"body":"{\"@qclass\":\"error\",\"name\":\"Error\",\"message\":\"client must be given GCI\"}","slots":[]}
ag-solo_1  | SwingSet: kernel: ##### KERNEL PANIC: bootstrap failure #####
ag-solo_1  | Maybe the chain has bumped and you need to rerun ag-setup-solo?
...
client_ag-solo_1 exited with code 1
```

`docker-compose.yml`;
```yaml
version: "2.2"
services:
  ag-solo:
    image: agoric/cosmic-swingset-solo:latest
    # ISSUE: 127.0.0.1? not a docker network?
    ports:
      - "$HOST_PORT:$PORT"
    volumes:
      - "ag-solo-state:/usr/src/app/solo"
      - "$HOME/.agoric:/root/.agoric"
    environment:
      - "AG_SOLO_BASEDIR=$SOLO_HOME"
    command: start
volumes:
  ag-solo-state:
```

`.env`:
```
SOLO_NAME=agoric
SOLO_HOME=agoric
PORT=8000
HOST_PORT=8000
```
