### ISSUE TITLE
build GitHub Action test list from package.json, or at least compare them automatically

### ISSUE THREAD

**Issue by warner** [Agoric/agoric-sdk#579]
Our CI configuration displays test results from each package on a separate line, making it a lot easier to see which test is failing:

![Screenshot_2020-02-19 Agoric agoric-sdk](https://user-images.githubusercontent.com/27146/74883543-079fd780-5326-11ea-97d1-bf859d2a8259.png)

To accomplish this, our `.github/workflows/test-all-packages.yml` has a list of steps, each of which runs a single package's tests:

```yml
    - name: yarn test (acorn-eventual-send)
      run: cd packages/acorn-eventual-send && yarn test
    - name: yarn test (agoric-cli)
      run: cd packages/agoric-cli && yarn test
    - name: yarn test (assert)
      run: cd packages/assert && yarn test
    - name: yarn test (autoswap-frontend)
      run: cd packages/autoswap-frontend && yarn test
   ...
```

The actual set of packages is defined by our top-level `package.json`, in the `workspaces:` key:

```json
  "workspaces": [
    "packages/assert",
    "packages/import-manager",
    "packages/make-promise",
    "packages/sparse-ints",
    "packages/registrar",
```

Having this defined in two separate places is a maintenance hassle and a footgun (it's easy to add a new package and forget to add it to the CI list, which means tests don't get run).

This ticket is about creating a script that parses both files and complains if the lists don't contain the same items. We can probably allow the order to differ: we currently keep `workspaces:` in dependency order (so that `yarn build` constructs things in the correct order), whereas `package.json` is currently alphabetical. (using `lerna` might allow us to keep both in alphabetical order). But the set of entries from one must equal the set from the other. The script should display the difference. Bonus points for a script that can generate a new `test-all-packages.yml` from the `package.json` and a template of some sort.
